apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-test-be-dep
spec:
  selector:
    matchLabels:
      app: docker-test-be
  replicas: 1
  template:
    metadata:
      labels:
        app: docker-test-be
    spec:
      # DB ì¤€ë¹??€ê¸?ì»¨í…Œ?´ë„ˆ
      # initContainers:
      #   - name: wait-for-db
      #     image: busybox
      #     command: ['sh', '-c', 'until nc -z docker-test-db-ser 3306; do echo "??waiting for db"; sleep 2; done;']
      containers:
      - name: docker-test-be-dep
        image: indy0322/docker_test_argo:1
        imagePullPolicy: Always
        ports:
        - containerPort: 7777
        env: 
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mariadb://docker-test-db-ser:3310/docker_test_db"
        - name: SPRING_DATASOURCE_USERNAME
          value: "swcamp"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "swcamp"




